fun main(args: Array<String>) {
   try {
    println("Hello")
   }
   catch(Exception e) {
    println("Hello")
   }
}